### ISSUE TITLE
Undefined index: pure_css on first install

### ISSUE THREAD

**Issue by PaulHoza** [backdrop-contrib/afterlight_tribute#1]
I just put this theme onto a new Backdrop install and I'm seeing this error when I go to the /admin/appearance/settings/afterlight_tribute admin page:

```
Notice: Undefined index: pure_css in theme_get_setting() (line 1429 of /home/example/public_html/core/includes/theme.inc).
```

For now, also installing the PureCSS theme (https://github.com/backdrop-contrib/pure_css) seems to get rid of this error in Afterlight Tribute, but clearly this isn't ideal.

Thanks.  I'll see if I can dig into this after I get past this deadline I'm on. :)

**Comment by biolithic** [comment]
My bad Paul, it is a error I can fix tonight - a setting to optionally
include a CSS library for buttons etc from a cdn or not

**Comment by biolithic** [comment]
appears to be fixed in https://github.com/backdrop-contrib/afterlight_tribute/tree/1.x-1.3.0
